DOMAIN = "wework_notify2"

# 环境变量名
ENV_WEWORK_NAME = "WEWORK_NAME"
ENV_WEWORK_CORPID = "WEWORK_CORPID"
ENV_WEWORK_AGENTID = "WEWORK_AGENTID"
ENV_WEWORK_SECRET = "WEWORK_SECRET"
ENV_WEWORK_TOUSER = "WEWORK_TOUSER"
